### Домашнее задание «Библиотека numpy. Вычислительные задачи»



### Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [5]:
import numpy as np

#### Вариант 1

In [20]:
N = 10
np.arange(0, N)[::-1]


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### Вариант 2

In [22]:
N = 10
np.arange(N-1, -1,-1)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

#### Решение
1. Создаем диагональную матрицу

In [33]:
N = 10
matrix = np.diag(np.arange(N, 0, -1))
print(matrix)

[[10  0  0  0  0  0  0  0  0  0]
 [ 0  9  0  0  0  0  0  0  0  0]
 [ 0  0  8  0  0  0  0  0  0  0]
 [ 0  0  0  7  0  0  0  0  0  0]
 [ 0  0  0  0  6  0  0  0  0  0]
 [ 0  0  0  0  0  5  0  0  0  0]
 [ 0  0  0  0  0  0  4  0  0  0]
 [ 0  0  0  0  0  0  0  3  0  0]
 [ 0  0  0  0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0  0  0  0  1]]


#### Вариант 1

In [40]:
print('сумма: {} '.format(sum(sum(matrix))))

сумма: 55 


#### Вариант 2

In [43]:
print('сумма: {} '.format(matrix.sum()))

сумма: 55 


#### Вариант 3

Более оптимальный, т.к. считает значения только по диагонале.

In [46]:
a = len(matrix)
summ = 0
for i in range(a):
    summ += matrix[i][i]
print('сумма: ', summ)

сумма:  55


### Задание 3
Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [28]:
from numpy import linalg

In [29]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )            # коэффициенты при переменных в левой части уравнения

b=np.array( [4, 12, -3] )                                      # значения в правой части уравнения

linalg.solve(a, b)                                             # решение

array([ 0.46666667,  3.84444444, -5.55555556])

In [30]:
# проверка верности

np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

### Задание 4
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [ ]:
from IPython.display import Image
Image("user_matrix.JPG")

Матрица в виде numpy array

In [85]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [ ]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [29]:
# Подсчет косинуса угла между векторами a, b по их координатам

def cosine( a, b ):
  
    aLength = np.linalg.norm( a )              # длины векторов
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

#### Вариант 1

In [94]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

cosinus_max = 0
k = 0

for i in users_stats:
    cosine_ab = cosine(next_user_stats, i)
    if cosine_ab >= cosinus_max:
        cosinus_max = cosine_ab
        k = i
print('Выбор наиболее похожего покупателя:', k, 'cosinus =', cosinus_max)

Выбор наиболее похожего покупателя: [0 1 1 0 0 0] cosinus = 0.9486832980505138


#### Вариант 2

In [92]:
# применим cosine к каждой строке матрицы users_stats. В numpy для этого есть функция apply_along_axis

muls = np.apply_along_axis(cosine, 1, users_stats, next_user_stats)

In [88]:
# Функция np.argmax находит индекс элемента, который соответствует максимальному значению массива (нумерация с нуля):
best_user = np.argmax(muls)

In [93]:
print('Самый похожий пользователь  - номер', best_user)

Самый похожий пользователь  - номер 7
