### Домашнее задание к занятию "Классификация: Логистическая регрессия и SVM"

Имеются данные adult.csv (см. в материалах к занятию).

Целевой переменной является уровень дохода income (крайний правый столбец).

Описание признаков можно найти по ссылке www.cs.toronto.edu...etail.html

Вам необходимо построить модели логистической регрессии и SVM, которые предсказывает уровень дохода человека.

Вывести качество полученных моделей на тестовой выборке, используя функцию score у модели.

#### 1. Построение логистической регрессии

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv( 'C:\\Users\\2-hom\\Documents\\Data_analysis\\Машинное обучение\\Занятие_2\\Лекция_2\\adult.csv' )
data.head()

age  workclass  fnlwgt     education  educational-num      marital-status  \
0   25    Private  226802          11th                7       Never-married   
1   38    Private   89814       HS-grad                9  Married-civ-spouse   
2   28  Local-gov  336951    Assoc-acdm               12  Married-civ-spouse   
3   44    Private  160323  Some-college               10  Married-civ-spouse   
4   18          ?  103497  Some-college               10       Never-married   

          occupation relationship   race  gender  capital-gain  capital-loss  \
0  Machine-op-inspct    Own-child  Black    Male             0             0   
1    Farming-fishing      Husband  White    Male             0             0   
2    Protective-serv      Husband  White    Male             0             0   
3  Machine-op-inspct      Husband  Black    Male          7688             0   
4                  ?    Own-child  White  Female             0             0   

   hours-per-week native-country income  
0              40  United-States  <=50K  
1              50  United-States  <=50K  
2              40  United-States   >50K  
3              40  United-States   >50K  
4              30  United-States  <=50K

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   age              48842 non-null  int64 
 1   workclass        48842 non-null  object
 2   fnlwgt           48842 non-null  int64 
 3   education        48842 non-null  object
 4   educational-num  48842 non-null  int64 
 5   marital-status   48842 non-null  object
 6   occupation       48842 non-null  object
 7   relationship     48842 non-null  object
 8   race             48842 non-null  object
 9   gender           48842 non-null  object
 10  capital-gain     48842 non-null  int64 
 11  capital-loss     48842 non-null  int64 
 12  hours-per-week   48842 non-null  int64 
 13  native-country   48842 non-null  object
 14  income           48842 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.6+ MB


In [4]:
print('Для age пустых строк {}'.format( len( data[ pd.isnull( data['age'] ) ] ) ))
print('Для workclass пустых строк {}'.format( len( data[ pd.isnull( data['workclass'] ) ] ) ))
print('Для fnlwgt пустых строк {}'.format( len( data[ pd.isnull( data['fnlwgt'] ) ] ) ))
print('Для education пустых строк {}'.format( len( data[ pd.isnull( data['education'] ) ] ) ))
print('Для educational-num пустых строк {}'.format( len( data[ pd.isnull( data['educational-num'] ) ] ) ))
print('Для marital-status пустых строк {}'.format( len( data[ pd.isnull( data['marital-status'] ) ] ) ))
print('Для occupation пустых строк {}'.format( len( data[ pd.isnull( data['occupation'] ) ] ) ))
print('Для relationship пустых строк {}'.format( len( data[ pd.isnull( data['relationship'] ) ] ) ))
print('Для race пустых строк {}'.format( len( data[ pd.isnull( data['race'] ) ] ) ))
print('Для gender пустых строк {}'.format( len( data[ pd.isnull( data['gender'] ) ] ) ))
print('Для capital-gain пустых строк {}'.format( len( data[ pd.isnull( data['capital-gain'] ) ] ) ))
print('Для capital-loss пустых строк {}'.format( len( data[ pd.isnull( data['capital-loss'] ) ] ) ))
print('Для  hours-per-week пустых строк {}'.format( len( data[ pd.isnull( data['hours-per-week'] ) ] ) ))
print('Для native-country пустых строк {}'.format( len( data[ pd.isnull( data['native-country'] ) ] ) ))
print('Для income  пустых строк {}'.format( len( data[ pd.isnull( data['income'] ) ] ) ))


Для age пустых строк 0
Для workclass пустых строк 0
Для fnlwgt пустых строк 0
Для education пустых строк 0
Для educational-num пустых строк 0
Для marital-status пустых строк 0
Для occupation пустых строк 0
Для relationship пустых строк 0
Для race пустых строк 0
Для gender пустых строк 0
Для capital-gain пустых строк 0
Для capital-loss пустых строк 0
Для  hours-per-week пустых строк 0
Для native-country пустых строк 0
Для income  пустых строк 0


In [5]:
from sklearn.linear_model import LogisticRegression

In [6]:
# выбитраем признаки
selectedColumns = data[ [ 'age', 'workclass', 'education', 'educational-num', 'marital-status', 'occupation', 'race', 'gender', 'hours-per-week', 'native-country', 'income' ] ]

# столбцы 'workclass', 'education', 'marital-status', 'occupation', 'race', 'gender', 'native-country' являются категориальными переменными
# переведем их в значения 0 и 1, добавив столбцы с соответствующими названиями
X = pd.get_dummies( selectedColumns, columns = [ 'workclass', 'education', 'marital-status', 'occupation', 'race', 'gender', 'native-country'] )

# столбец income является целевой переменной, удаляем его из X
del X['income']
X.head()

age  educational-num  hours-per-week  workclass_?  workclass_Federal-gov  \
0   25                7              40            0                      0   
1   38                9              50            0                      0   
2   28               12              40            0                      0   
3   44               10              40            0                      0   
4   18               10              30            1                      0   

   workclass_Local-gov  workclass_Never-worked  workclass_Private  \
0                    0                       0                  1   
1                    0                       0                  1   
2                    1                       0                  0   
3                    0                       0                  1   
4                    0                       0                  0   

   workclass_Self-emp-inc  workclass_Self-emp-not-inc  ...  \
0                       0                           0  ...   
1                       0                           0  ...   
2                       0                           0  ...   
3                       0                           0  ...   
4                       0                           0  ...   

   native-country_Portugal  native-country_Puerto-Rico  \
0                        0                           0   
1                        0                           0   
2                        0                           0   
3                        0                           0   
4                        0                           0   

   native-country_Scotland  native-country_South  native-country_Taiwan  \
0                        0                     0                      0   
1                        0                     0                      0   
2                        0                     0                      0   
3                        0                     0                      0   
4                        0                     0                      0   

   native-country_Thailand  native-country_Trinadad&Tobago  \
0                        0                               0   
1                        0                               0   
2                        0                               0   
3                        0                               0   
4                        0                               0   

   native-country_United-States  native-country_Vietnam  \
0                             1                       0   
1                             1                       0   
2                             1                       0   
3                             1                       0   
4                             1                       0   

   native-country_Yugoslavia  
0                          0  
1                          0  
2                          0  
3                          0  
4                          0  

[5 rows x 99 columns]

In [7]:
# целевая переменная (столбец income) снова является категориальной
# переведем значения столбца в числа, оставив один столбец

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [8]:
le.fit( data['income'] )

LabelEncoder()

In [9]:
le.classes_

array(['<=50K', '>50K'], dtype=object)

In [10]:
# пример "расшировки" столбца income

le.transform( [ '<=50K', '>50K' ] )

array([0, 1], dtype=int64)

In [11]:
# записываем в переменную y преобразованный столбец income

y = pd.Series( data = le.transform( data['income'] ) )
y.head()

0    0
1    0
2    1
3    1
4    0
dtype: int32

In [12]:
from sklearn.pipeline import make_pipeline # используем пайплайны для удобства
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split 

model = make_pipeline(StandardScaler(), LogisticRegression(max_iter=1000))

In [13]:
model = LogisticRegression() # берем в качестве модели логистическую регресиию из scikit-learn

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [15]:
X_train.head()

age  educational-num  hours-per-week  workclass_?  \
42392   25                9              40            0   
14623   64                9              17            0   
27411   29                9              40            0   
1288    28               11              50            0   
7078    22                9               1            0   

       workclass_Federal-gov  workclass_Local-gov  workclass_Never-worked  \
42392                      0                    0                       0   
14623                      0                    0                       0   
27411                      0                    0                       0   
1288                       0                    0                       0   
7078                       0                    0                       0   

       workclass_Private  workclass_Self-emp-inc  workclass_Self-emp-not-inc  \
42392                  1                       0                           0   
14623                  1                       0                           0   
27411                  1                       0                           0   
1288                   1                       0                           0   
7078                   1                       0                           0   

       ...  native-country_Portugal  native-country_Puerto-Rico  \
42392  ...                        0                           0   
14623  ...                        0                           0   
27411  ...                        0                           0   
1288   ...                        0                           0   
7078   ...                        0                           0   

       native-country_Scotland  native-country_South  native-country_Taiwan  \
42392                        0                     0                      0   
14623                        0                     0                      0   
27411                        0                     0                      0   
1288                         0                     0                      0   
7078                         0                     0                      0   

       native-country_Thailand  native-country_Trinadad&Tobago  \
42392                        0                               0   
14623                        0                               0   
27411                        0                               0   
1288                         0                               0   
7078                         0                               0   

       native-country_United-States  native-country_Vietnam  \
42392                             1                       0   
14623                             1                       0   
27411                             0                       0   
1288                              1                       0   
7078                              1                       0   

       native-country_Yugoslavia  
42392                          0  
14623                          0  
27411                          0  
1288                           0  
7078                           0  

[5 rows x 99 columns]

In [16]:
X

age  educational-num  hours-per-week  workclass_?  \
0       25                7              40            0   
1       38                9              50            0   
2       28               12              40            0   
3       44               10              40            0   
4       18               10              30            1   
...    ...              ...             ...          ...   
48837   27               12              38            0   
48838   40                9              40            0   
48839   58                9              40            0   
48840   22                9              20            0   
48841   52                9              40            0   

       workclass_Federal-gov  workclass_Local-gov  workclass_Never-worked  \
0                          0                    0                       0   
1                          0                    0                       0   
2                          0                    1                       0   
3                          0                    0                       0   
4                          0                    0                       0   
...                      ...                  ...                     ...   
48837                      0                    0                       0   
48838                      0                    0                       0   
48839                      0                    0                       0   
48840                      0                    0                       0   
48841                      0                    0                       0   

       workclass_Private  workclass_Self-emp-inc  workclass_Self-emp-not-inc  \
0                      1                       0                           0   
1                      1                       0                           0   
2                      0                       0                           0   
3                      1                       0                           0   
4                      0                       0                           0   
...                  ...                     ...                         ...   
48837                  1                       0                           0   
48838                  1                       0                           0   
48839                  1                       0                           0   
48840                  1                       0                           0   
48841                  0                       1                           0   

       ...  native-country_Portugal  native-country_Puerto-Rico  \
0      ...                        0                           0   
1      ...                        0                           0   
2      ...                        0                           0   
3      ...                        0                           0   
4      ...                        0                           0   
...    ...                      ...                         ...   
48837  ...                        0                           0   
48838  ...                        0                           0   
48839  ...                        0                           0   
48840  ...                        0                           0   
48841  ...                        0                           0   

       native-country_Scotland  native-country_South  native-country_Taiwan  \
0                            0                     0                      0   
1                            0                     0                      0   
2                            0                     0                      0   
3                            0                     0                      0   
4                            0                     0                      0   
...                        ...                   ...                    ...   
48837                        0            

In [17]:
# обучаем на части датасета (train)

model.fit(X_train, y_train)
predictions = model.predict(X_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [18]:
predictions[:5] # посмотрим как выглядят наши предсказания

array([0, 0, 0, 0, 1])

In [19]:
model.predict(X_test) # получаем массив

array([0, 0, 0, ..., 0, 0, 0])

In [20]:
model.predict_proba(X_test)

array([[0.9791584 , 0.0208416 ],
       [0.74003161, 0.25996839],
       [0.80009037, 0.19990963],
       ...,
       [0.96113605, 0.03886395],
       [0.64294698, 0.35705302],
       [0.96773403, 0.03226597]])

In [21]:
predictions[:5]

array([0, 0, 0, 0, 1])

In [22]:
y_pred = model.predict(X_test)   # прогнозные данные модели
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [23]:
# сравним пронозы, построенные моделью, с фактом
res_df = X_test.copy()

res_df['y_pred'] = y_pred
res_df['y_test'] = y_test
res_df

age  educational-num  hours-per-week  workclass_?  \
7762    56                9              40            0   
23881   25                9              40            0   
30507   43               13              40            0   
28911   32                9              40            0   
19484   39               13              30            0   
...    ...              ...             ...          ...   
15938   20                9              38            0   
27828   23                9              25            0   
28449   38               10              40            0   
5647    61                9              50            0   
27058   53                9              40            0   

       workclass_Federal-gov  workclass_Local-gov  workclass_Never-worked  \
7762                       0                    0                       0   
23881                      0                    0                       0   
30507                      0                    0                       0   
28911                      0                    0                       0   
19484                      0                    0                       0   
...                      ...                  ...                     ...   
15938                      0                    0                       0   
27828                      0                    0                       0   
28449                      1                    0                       0   
5647                       0                    0                       0   
27058                      0                    0                       0   

       workclass_Private  workclass_Self-emp-inc  workclass_Self-emp-not-inc  \
7762                   1                       0                           0   
23881                  1                       0                           0   
30507                  1                       0                           0   
28911                  1                       0                           0   
19484                  1                       0                           0   
...                  ...                     ...                         ...   
15938                  1                       0                           0   
27828                  1                       0                           0   
28449                  0                       0                           0   
5647                   0                       0                           1   
27058                  1                       0                           0   

       ...  native-country_Scotland  native-country_South  \
7762   ...                        0                     0   
23881  ...                        0                     0   
30507  ...                        0                     0   
28911  ...                        0                     0   
19484  ...                        0                     0   
...    ...                      ...                   ...   
15938  ...                        0                     0   
27828  ...                        0                     0   
28449  ...                        0                     0   
5647   ...                        0                     0   
27058  ...                        0                     0   

       native-country_Taiwan  native-country_Thailand  \
7762                       0                        0   
23881                      0                        0   
30507                      0                        0   
28911                      0                        0   
19484                      0                        0   
...                      ...                      ...   
15938                      0                        0   
27828                      0                        0   
28449                      0                        0   
5647                       0                        0   
27058                      0            

In [24]:
# Оценим точность предсказания на обучающей и тестовой выборках

In [25]:
model.score(X_train, y_train) # метод возвращает значение коэффициента детерминации - точность предсказания на обучающей выборке

0.8324022346368715

In [26]:
model.score(X_test, y_test) # метод возвращает значение коэффициента детерминации - точность предсказания на тестовой выборке

0.8388725858186037

#### 2. Построение модели  SVM

In [27]:
from sklearn.svm import SVC
# используем пайплайны
clf = make_pipeline(StandardScaler(), SVC(gamma='auto')) 
clf.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('svc', SVC(gamma='auto'))])

In [28]:
clf.score(X_train, y_train) 

0.840299511538799

In [29]:
clf.score(X_test, y_test)

0.8405787210810073

In [30]:
svc = SVC(gamma='auto')
svc.fit(X_train, y_train)

SVC(gamma='auto')

In [31]:
svc.score(X_train, y_train)

0.8343034309280762

In [32]:
svc.score(X_test, y_test)

0.8401692486180304