## Домашнее задание "Продвинутая линейная алгебра"

### Уровень 0:

Придумайте матрицы, которые обладают следующими свойствами:

a) диагональная, ортогональная, но не единичная(!):

b) верхнетреугольная, ортогональная:

c) нижнетреугольная, ортогональная: 

d) матрица, у которой определитель = 1, и все элементы не равны 0:

e) матрица (3x3), у которой определитель = 1:

P.S. Во всех пунктах ответом должна быть ненулевая матрица размерности не менее 2!

In [1]:
import numpy as np
import pylab as pl
import warnings

from matplotlib import pyplot as plt
from scipy import linalg
from sklearn.datasets import load_digits
from sklearn.decomposition import TruncatedSVD
from sklearn.ensemble import RandomForestClassifier
warnings.filterwarnings("ignore")

In [2]:
# a) диагональная, ортогональная, но не единичная(!):

m1 = np.array([[1, 0], [0, -1]])
m1

array([[ 1,  0],
       [ 0, -1]])

In [3]:
# проверка на ортогональность матрицы m1
m1t = m1.transpose()
m1.dot(m1t)


array([[1, 0],
       [0, 1]])

In [4]:
# b) верхнетреугольная, ортогональная:
m2 = np.triu([[1, 0], [0, -1]])
m2

array([[ 1,  0],
       [ 0, -1]])

In [5]:
# проверка на ортогональность матрицы m2
m2t = m1.transpose()
m2.dot(m1t)

array([[1, 0],
       [0, 1]])

In [6]:
# c) нижнетреугольная, ортогональная: 
m3 = np.tril([[1, 0], [0, -1]])
m3

array([[ 1,  0],
       [ 0, -1]])

In [7]:
# проверка на ортогональность матрицы m3
m3t = m1.transpose()
m3.dot(m1t)

array([[1, 0],
       [0, 1]])

In [8]:
# d) матрица, у которой определитель = 1, и все элементы не равны 0:
m4 = np.array([[2, 3], [1, 2]])
det4 = np.linalg.det(m4)
print(m4)
print(det4)

[[2 3]
 [1 2]]
1.0


Найдите собственные значения и собственные вектора матриц:

In [11]:
m6 = np.array([[2, 2],
              [1, 3]])
print(m6)

[[2 2]
 [1 3]]


In [12]:
w, v = np.linalg.eig(m6)

for i in range(len(w)):
    print("Собственное значение " + str(w[i]))
    print("соответствующий ему собственный вектор " + str(v[:,i]))

Собственное значение 1.0
соответствующий ему собственный вектор [-0.89442719  0.4472136 ]
Собственное значение 4.0
соответствующий ему собственный вектор [-0.70710678 -0.70710678]


###  Уровень 1:

Найдите спектральное разложение матрицы:

In [13]:
m8 = np.array([[1, 2],
              [2,3]])
print(m8)

[[1 2]
 [2 3]]


In [14]:
a, U = linalg.eig(m8)
print('Eigenvalues:')
print(np.array(a, dtype=float))
print('\nEigenvectors:')
print(U)

Eigenvalues:
[-0.23606798  4.23606798]

Eigenvectors:
[[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


In [15]:
print(np.array(U.dot(np.diag(a)).dot(U.T), dtype=float))

[[1. 2.]
 [2. 3.]]
